### ISSUE TITLE
The compilation

### ISSUE THREAD

**Issue by dorily21** [tap3edit/tap3xml#3]
Hi, please help me with the compilation
The compilation has two steps:
    make parsers
    make 
when I execute the first step, I get the following error:

>make parsers
flex --nounistd -B -Pasn1 -oasn1_lexer.cpp asn1_lexer.l
flex: unknown flag '-'.  For usage, try
        flex --help
*** Error code 1
make: Fatal error: Command failed for target `asn1_lexer'

I have the following version of flex

>flex --version
flex version 2.5.4

Thank you!

**Comment by tap3edit** [comment]
The distribution already includes the parser's source code: asn1_parser.cpp, asn1_parser.hpp, xml_parser.cpp, xml_parser.hpp, so you wouldn't really need to run "make parsers". So try just running "make". If you don't have those files, download the package again.

Now I am not sure why you get the error. Try running manually the command:

`flex --nounistd -B -Pasn1 -oasn1_lexer.cpp asn1_lexer.l`

If you still get the error you can upgrade your flex version to 2.6.4 which is the version I am using.

**Comment by dorily21** [comment]
Thank you very much! I was able to compile correctly with make:

>make
g++ -g -Wall -Wno-unknown-pragmas  -c -o global.o global.cpp
g++ -g -Wall -Wno-unknown-pragmas  -c -o Buffin.o Buffin.cpp
g++ -g -Wall -Wno-unknown-pragmas  -c -o Buffout.o Buffout.cpp
g++ -g -Wall -Wno-unknown-pragmas  -c -o Asn.o Asn.cpp
g++ -g -Wall -Wno-unknown-pragmas  -c -o AsnItem.o AsnItem.cpp
g++ -g -Wall -Wno-unknown-pragmas  -c -o TreeItem.o TreeItem.cpp
g++ -g -Wall -Wno-unknown-pragmas  -c -o TreeParser.o TreeParser.cpp
g++ -g -Wall -Wno-unknown-pragmas  -c -o Xml.o Xml.cpp
g++ -g -Wall -Wno-unknown-pragmas  -c -o XmlItem.o XmlItem.cpp
g++ -g -Wall -Wno-unknown-pragmas  -c -o asn1_lexer.o asn1_lexer.cpp
g++ -g -Wall -Wno-unknown-pragmas  -c -o asn1_parser.o asn1_parser.cpp
g++ -g -Wall -Wno-unknown-pragmas  -c -o xml_lexer.o xml_lexer.cpp
g++ -g -Wall -Wno-unknown-pragmas  -c -o xml_parser.o xml_parser.cpp
g++ -g -Wall -Wno-unknown-pragmas  -c -o tap3xml.o tap3xml.cpp
g++ -g -Wall -Wno-unknown-pragmas  -c -o TapInfo.o TapInfo.cpp
g++ tap3xml.o TapInfo.o asn1_lexer.o asn1_parser.o xml_lexer.o xml_parser.o global.o Buffin.o Buffout.o Asn.o AsnItem.o TreeItem.o TreeParser.o Xml.o XmlItem.o -o tap3xml  # -pg
g++ -g -Wall -Wno-unknown-pragmas  -c -o nrt2xml.o nrt2xml.cpp
g++ -g -Wall -Wno-unknown-pragmas  -c -o NrtInfo.o NrtInfo.cpp
g++ nrt2xml.o NrtInfo.o asn1_lexer.o asn1_parser.o xml_lexer.o xml_parser.o global.o Buffin.o Buffout.o Asn.o AsnItem.o TreeItem.o TreeParser.o Xml.o XmlItem.o -o nrt2xml  # -pg

great! excellent
